name: hair_salon_nearby
description: A Hair Salon Project

#This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  #API Connection  
  http: ^1.1.0
  dio: ^5.3.3

  #onboarding
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

  #Cache & Storage
  hive_flutter: ^1.1.0
  get_it: ^7.6.4

  #Image Operations
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  like_button: ^2.0.5

  #Input
  mask_input_formatter: ^0.0.3

  #State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

  #localization
  easy_localization: ^3.0.3

  #Json Operations
  json_annotation: ^4.8.1

  ################
  intl: ^0.18.1

  #File Operations
  better_open_file: ^3.6.4

  #Cryptology
  cryptography: ^2.7.0
  
  #Navigation
  auto_route: ^7.8.3
  stylish_bottom_bar: ^1.0.3

  #Version compare
  version_comparator: ^1.0.2

  #Responsive Design
  responsive_framework: ^1.1.1
  responsive_builder: ^0.7.0
  flutter_native_splash: ^2.3.2

  #Device
  device_preview: ^1.1.0

  #env
  envied: ^0.3.0+3

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
    
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.1
  flutter_gen_runner: ^5.3.2
  envied_generator: ^0.3.0+3

  #Json Operation
  json_serializable: ^6.7.1

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/images/png/ic_logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. 
  flutter_lints: ^2.0.3

flutter_gen:
  output: lib/utils/gen/
  line_length: 120

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AppColors

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/images/png/ic_logo_horizontal.png
    - assets/images/png/ic_women_hairdresser_background.png
    - assets/images/png/ic_men_hairdresser_background.png
    - assets/images/png/ic_beauty_centre_background.png
    - assets/images/png/ic_men_logo_and_name.png
    - assets/images/png/ic_beauty_centre_logo_and_name.png
    - assets/images/png/ic_primary_beauty_centre_logo_and_name.png
    - assets/images/png/ic_women_logo_and_name.png
    - assets/images/png/ic_primary_women_logo_and_name.png
    - assets/images/png/ic_advertisement_area.png
    - assets/images/png/ic_splash_background.png
    - assets/images/png/ic_splash_logo.png
    - assets/images/png/ic_logo.png
    - assets/images/jpg/
    - assets/fonts/
    - assets/translations/
    - assets/envs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf